PrototypeApp({
  name:'智服中枢',en:'AI CUSTOMER SERVICE',color:'#6366f1',color2:'#a855f7',user:'许清和',role:'客服班组长',badge:16,
  greeting:'服务运营中心',subtitle:'当前服务平稳，售后队列有 3 位客户等待超过 1 分钟。',entity:'客户会话',metricLabel:'等待 / 时长',
  nav:['服务概览','会话工作台','工单中心','实时监控','机器人运营','知识库','智能质检','服务分析','系统设置'],
  kpis:[{label:'今日会话',value:'1,286',trend:'↑ 12.8%'},{label:'AI 自助解决率',value:'61.4%',trend:'↑ 4.6%'},{label:'人工首响',value:'24秒',trend:'↓ 18.2%'},{label:'客户满意度',value:'94.8%',trend:'↑ 2.1%'}],
  chartTitle:'会话量与 AI 解决趋势',donutTitle:'咨询问题分布',focusTitle:'实时排队会话',categories:['订单物流','退换售后','账户权益'],
  rows:[{name:'林女士 · 订单物流咨询',code:'CV-20260707-1286',status:'排队中',value:'等待 01:42',progress:86,owner:'售后技能组'},{name:'陈先生 · 申请退货',code:'CV-20260707-1279',status:'人工接待',value:'进行 06:18',progress:63,owner:'坐席 A-018'},{name:'游客 8821 · 账户异常',code:'CV-20260707-1268',status:'风险升级',value:'等待 02:31',progress:92,owner:'专家队列'},{name:'宋女士 · 优惠券问题',code:'CV-20260707-1251',status:'AI 接待',value:'进行 01:06',progress:35,owner:'智能助手'},{name:'VIP-0038 · 发票修改',code:'CV-20260707-1239',status:'待客户回复',value:'静默 04:20',progress:48,owner:'坐席 A-006'}],
  activities:['AI 助手将一条低置信会话转入售后队列','坐席 A-018 使用并编辑了知识推荐回复','知识「七天无理由退货规则」发布 V3 版本','质检系统识别到 1 条隐私风险会话','工单 TK-202607-0921 已解决并邀请评价'],
  pages:{
    1:{kind:'kanban',entity:'客户会话',description:'统一处理机器人、排队、人工接待和待回复会话，完整保留客户上下文。',metricLabel:'等待/会话时长',ownerLabel:'当前接待',primaryAction:'发起模拟会话',codePrefix:'CV',initialStatus:'机器人接待',activeStatus:'人工接待',reviewStatus:'待解决',advanceAction:'接入/结束会话',categories:['订单物流','退换售后','账户权益'],kanban:['机器人与排队','人工接待中','待回复/结束'],rows:[{name:'林女士 · 订单物流咨询',code:'CV-20260708-1286',status:'排队中',value:'等待 01:42',progress:36,owner:'售后技能组'},{name:'陈先生 · 申请退货',code:'CV-20260708-1279',status:'人工接待',value:'进行 06:18',progress:64,owner:'坐席 A-018'},{name:'VIP-0038 · 发票修改',code:'CV-20260708-1239',status:'待客户回复',value:'静默 04:20',progress:86,owner:'坐席 A-006'}]},
    2:{entity:'客服工单',description:'从会话创建工单，跟踪分类、优先级、负责人、SLA、协作评论和解决方案。',metricLabel:'SLA 剩余',ownerLabel:'工单负责人',primaryAction:'新建工单',codePrefix:'TK',initialStatus:'新建',activeStatus:'处理中',reviewStatus:'待解决',advanceAction:'推进工单状态',categories:['退款售后','账户问题','物流异常'],rows:[{name:'订单退款审核异常',code:'TK-202607-0921',status:'处理中',value:'剩余 1小时20分',progress:62,owner:'坐席 A-018'},{name:'物流轨迹长期未更新',code:'TK-202607-0916',status:'待物流反馈',value:'剩余 3小时',progress:48,owner:'售后技能组'},{name:'账户实名认证失败',code:'TK-202607-0908',status:'已升级',value:'已超时 18分',progress:88,owner:'专家队列'}]},
    3:{kind:'analytics',entity:'服务队列',description:'实时查看排队、最长等待、在线坐席、并发负载和 SLA 风险。',metricLabel:'队列负载',ownerLabel:'技能组',chartTitle:'实时会话与接通趋势',donutTitle:'队列负载构成',categories:['售后队列','订单队列','综合队列'],kpis:[{label:'排队人数',value:'18',trend:'↑ 3'},{label:'最长等待',value:'02:41',trend:'需关注'},{label:'在线坐席',value:'26/32',trend:'81%'},{label:'SLA 达成率',value:'94.6%',trend:'↑ 1.8%'}],rows:[{name:'售后技能队列',code:'QUEUE-AFTERSALE',status:'高负载',value:'92%',progress:92,owner:'12 名坐席'},{name:'订单物流队列',code:'QUEUE-ORDER',status:'正常',value:'68%',progress:68,owner:'8 名坐席'},{name:'VIP 专属队列',code:'QUEUE-VIP',status:'空闲',value:'34%',progress:34,owner:'4 名坐席'}]},
    4:{kind:'kanban',entity:'机器人场景',description:'配置意图样本、关联知识、回复策略、快捷按钮和转人工规则。',metricLabel:'命中/解决率',ownerLabel:'机器人运营',primaryAction:'新建机器人场景',codePrefix:'BOT',initialStatus:'草稿',activeStatus:'测试中',reviewStatus:'已发布',advanceAction:'发布场景版本',categories:['售前咨询','订单服务','售后服务'],kanban:['草稿','测试与调优','已发布'],rows:[{name:'退换货政策咨询',code:'BOT-SCENE-018',status:'已发布',value:'命中 86% / 解决 72%',progress:92,owner:'沈听澜'},{name:'订单物流查询',code:'BOT-SCENE-012',status:'运行中',value:'命中 91% / 解决 78%',progress:88,owner:'沈听澜'},{name:'账户安全异常',code:'BOT-SCENE-025',status:'测试中',value:'命中 68% / 转人工',progress:58,owner:'顾言川'}]},
    5:{entity:'知识文章',description:'管理知识分类、正文、相似问法、适用渠道、版本、审核与有效期。',metricLabel:'版本/命中量',ownerLabel:'知识负责人',primaryAction:'新建知识文章',codePrefix:'KB',initialStatus:'草稿',activeStatus:'审核中',reviewStatus:'已发布',advanceAction:'提交/发布知识',categories:['订单物流','退款售后','账户权益'],rows:[{name:'七天无理由退货规则',code:'KB-RET-0038',status:'已发布',value:'V3 · 命中 1,286',progress:96,owner:'沈听澜'},{name:'物流异常处理时效',code:'KB-LOG-0026',status:'待审核',value:'V2 · 命中 642',progress:72,owner:'许清和'},{name:'优惠券使用与失效说明',code:'KB-MKT-0019',status:'即将过期',value:'V4 · 命中 518',progress:54,owner:'顾言川'}]},
    6:{entity:'质检任务',description:'结合规则抽样和机器建议进行人工复核、证据引用、评分发布与申诉处理。',metricLabel:'质检得分',ownerLabel:'质检专员',primaryAction:'创建质检任务',codePrefix:'QC',initialStatus:'待质检',activeStatus:'复核中',reviewStatus:'申诉复核',advanceAction:'发布质检结果',categories:['随机抽样','风险命中','投诉会话'],rows:[{name:'会话 CV-1286 服务规范质检',code:'QC-260708-086',status:'待人工复核',value:'机器建议 86分',progress:42,owner:'顾言川'},{name:'隐私风险会话专项质检',code:'QC-260708-079',status:'高风险',value:'机器建议 62分',progress:68,owner:'顾言川'},{name:'坐席 A-018 质检申诉',code:'QC-APPEAL-021',status:'申诉中',value:'原分 78分',progress:84,owner:'客服班组长'}]},
    7:{kind:'analytics',entity:'客服指标',description:'分析会话量、自助解决、响应时长、一次解决率、满意度和知识负反馈。',metricLabel:'指标值',ownerLabel:'统计周期',chartTitle:'会话量与 AI 解决趋势',donutTitle:'问题分类构成',categories:['订单物流','退换售后','账户权益'],kpis:[{label:'今日会话',value:'1,286',trend:'↑ 12.8%'},{label:'AI 自助解决率',value:'61.4%',trend:'↑ 4.6%'},{label:'人工首响',value:'24秒',trend:'↓ 18.2%'},{label:'客户满意度',value:'94.8%',trend:'↑ 2.1%'}],rows:[{name:'AI 自助解决率',code:'KPI-AI-RESOLVE',status:'高于目标',value:'61.4%',progress:88,owner:'本周'},{name:'人工首次响应时长',code:'KPI-FRT',status:'达标',value:'24 秒',progress:92,owner:'今日'},{name:'一次解决率',code:'KPI-FCR',status:'需改善',value:'78.6%',progress:79,owner:'本周'}]},
    8:{kind:'settings',entity:'客服配置',description:'配置渠道、技能队列、路由优先级、坐席并发、SLA、敏感词与角色权限。',metricLabel:'当前配置',ownerLabel:'维护人',categories:['渠道','路由','安全'],rows:[{name:'Web 与 App 接入渠道',code:'SET-CHANNEL',status:'在线',value:'3 个渠道',progress:100,owner:'系统管理员'},{name:'技能队列与智能路由',code:'SET-ROUTE',status:'已启用',value:'4 个队列 / 8 条规则',progress:100,owner:'客服班组长'},{name:'坐席并发与工作时间',code:'SET-AGENT',status:'运行中',value:'并发上限 5',progress:100,owner:'系统管理员'},{name:'SLA 与敏感词策略',code:'SET-SAFETY',status:'待更新',value:'12 条策略',progress:74,owner:'质检专员'}]}
  },
  roles:[{name:'客服班组长',user:'许清和',scope:'本组数据',nav:[0,1,2,3,4,5,6,7,8],permissions:['create','edit','export','advance']},{name:'人工坐席',user:'坐席 A-018',scope:'个人数据',nav:[0,1,2,3,5],permissions:['create','edit','advance']},{name:'机器人运营',user:'沈听澜',scope:'全部数据',nav:[0,4,5,7],permissions:['create','edit','export']},{name:'质检专员',user:'顾言川',scope:'质量相关数据',nav:[0,2,6,7],permissions:['edit','export','advance']},{name:'系统管理员',user:'唐知微',scope:'全部数据',nav:[0,1,2,3,4,5,6,7,8],permissions:['export']}]
});
